variables:
  CONAN_REFERENCE: "pcl/1.8.1-rev-9dae1ea"
  CONAN_USERNAME: "sigth"
  CONAN_LOGIN_USERNAME: "sight"
  CONAN_CHANNEL: "stable"
  CONAN_STABLE_BRANCH_PATTERN: "stable/*"
  CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
  CONAN_ARCHS: x86_64
  CONAN_CPU_COUNT: 4

stages:
  - build

msvc2015:
  stage: build
  variables:
    CONAN_VISUAL_VERSIONS: "14"
    CONAN_USER_HOME: $CI_PROJECT_DIR
    CONAN_USE_CUDA: "False"
  script:
    - python build.py
  tags:
    - shell
    - windows

msvc2015-cuda:
  stage: build
  variables:
    CONAN_VISUAL_VERSIONS: "14"
    CONAN_USER_HOME: $CI_PROJECT_DIR
    CONAN_USE_CUDA: "True"
  script:
    - python build.py
  tags:
    - shell
    - windows

msvc2017:
  stage: build
  variables:
    CONAN_VISUAL_VERSIONS: "15"
    CONAN_USER_HOME: $CI_PROJECT_DIR
    CONAN_USE_CUDA: "False"
  script:
    - python build.py
  tags:
    - shell
    - windows

msvc2017-cuda:
  stage: build
  variables:
    CONAN_VISUAL_VERSIONS: "15"
    CONAN_USER_HOME: $CI_PROJECT_DIR
    CONAN_USE_CUDA: "True"
  script:
    - python build.py
  tags:
    - shell
    - windows

gcc-7:
  image: registry.lan.local:5000/docker-envdev-gcc7:dev
  stage: build
  variables:
    CONAN_GCC_VERSIONS: "7"
    CONAN_USE_CUDA: "False"
  script:
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    - python3 build.py

gcc-7-cuda:
  image: registry.lan.local:5000/docker-envdev-gcc7:dev
  stage: build
  variables:
    CONAN_GCC_VERSIONS: "7"
    CONAN_USE_CUDA: "True"
  script:
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    - python3 build.py

clang-6:
  image: registry.lan.local:5000/docker-envdev-clang6:dev
  stage: build
  variables:
    CONAN_CLANG_VERSIONS: "6.0"
    CONAN_USE_CUDA: "False"
  script:
    - export CC=/usr/bin/clang-6.0
    - export CXX=/usr/bin/clang++-6.0
    - python3 build.py

clang-6-cuda:
  image: registry.lan.local:5000/docker-envdev-clang6:dev
  stage: build
  variables:
    CONAN_CLANG_VERSIONS: "6.0"
    CONAN_USE_CUDA: "True"
  script:
    - export CC=/usr/bin/clang-6.0
    - export CXX=/usr/bin/clang++-6.0
    - python3 build.py