variables:
  CONAN_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  CONAN_PROJECT_NAME: $CI_PROJECT_NAME

stages:
  - build

before_script:
  - git -c http.sslVerify=false clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@git.ircad.fr/conan/conan.git

msvc2017:
  stage: build
  variables:
    CONAN_VISUAL_VERSIONS: "15"
    CONAN_USER_HOME: $CI_PROJECT_DIR
    CONAN_CUDA: "None"
  script:
    - python conan/gitlab-ci/build.py
  tags:
    - shell
    - windows

msvc2017-cuda:
  stage: build
  variables:
    CONAN_VISUAL_VERSIONS: "15"
    CONAN_USER_HOME: $CI_PROJECT_DIR
    CONAN_CUDA: "10.0"
  script:
    - python conan/gitlab-ci/build.py
  tags:
    - shell
    - windows

mint18-clang-6:
  image: ${DOCKER_ENVDEV_CLANG6}
  stage: build
  variables:
    CONAN_CLANG_VERSIONS: "6.0"
    CONAN_CUDA: "None"
  script:
    - export CC=/usr/bin/clang-6.0
    - export CXX=/usr/bin/clang++-6.0
    - python3 conan/gitlab-ci/build.py

mint18-clang-6-cuda:
  image: ${DOCKER_ENVDEV_CLANG6}
  stage: build
  variables:
    CONAN_CLANG_VERSIONS: "6.0"
    CONAN_CUDA: "9.2"
  script:
    - export CC=/usr/bin/clang-6.0
    - export CXX=/usr/bin/clang++-6.0
    - python3 conan/gitlab-ci/build.py

mint19-gcc-7:
  image: ${DOCKER_ENVDEV_MINT19}
  stage: build
  variables:
    CONAN_GCC_VERSIONS: "7"
    CONAN_CUDA: "None"
  script:
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    - python3 conan/gitlab-ci/build.py

mint19-gcc-7-cuda:
  image: ${DOCKER_ENVDEV_MINT19}
  stage: build
  variables:
    CONAN_GCC_VERSIONS: "7"
    CONAN_CUDA: "10.0"
  script:
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    - python3 conan/gitlab-ci/build.py

macos-mojave:
  stage: build
  variables:
    CONAN_APPLE_CLANG_VERSIONS: "10.0"
    CONAN_USER_HOME: $CI_PROJECT_DIR
  script:
    - python3 conan/gitlab-ci/build.py
  tags:
    - mojave