variables:
  CONAN_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  CONAN_PROJECT_NAME: $CI_PROJECT_NAME

stages:
  - build

msvc2017:
  stage: build
  variables:
    CONAN_VISUAL_VERSIONS: "15"
    CONAN_USER_HOME: $CI_PROJECT_DIR
    CONAN_USE_CUDA: "False"
  script:
    - git -c http.sslVerify=false clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lan.local/conan/conan.git
    - python conan/gitlab-ci/build.py
  tags:
    - shell
    - windows

msvc2017-cuda:
  stage: build
  variables:
    CONAN_VISUAL_VERSIONS: "15"
    CONAN_USER_HOME: $CI_PROJECT_DIR
    CONAN_USE_CUDA: "True"
  script:
    - git -c http.sslVerify=false clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lan.local/conan/conan.git
    - python conan/gitlab-ci/build.py
  tags:
    - shell
    - windows

gcc-7:
  image: registry.lan.local:5000/docker-envdev-gcc7:dev
  stage: build
  variables:
    CONAN_GCC_VERSIONS: "7"
    CONAN_USE_CUDA: "False"
  script:
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    - git -c http.sslVerify=false clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lan.local/conan/conan.git
    - python3 conan/gitlab-ci/build.py

gcc-7-cuda:
  image: registry.lan.local:5000/docker-envdev-gcc7:dev
  stage: build
  variables:
    CONAN_GCC_VERSIONS: "7"
    CONAN_USE_CUDA: "True"
  script:
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    - git -c http.sslVerify=false clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lan.local/conan/conan.git
    - python3 conan/gitlab-ci/build.py

clang-6:
  image: registry.lan.local:5000/docker-envdev-clang6:dev
  stage: build
  variables:
    CONAN_CLANG_VERSIONS: "6.0"
    CONAN_USE_CUDA: "False"
  script:
    - export CC=/usr/bin/clang-6.0
    - export CXX=/usr/bin/clang++-6.0
    - git -c http.sslVerify=false clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lan.local/conan/conan.git
    - python3 conan/gitlab-ci/build.py

clang-6-cuda:
  image: registry.lan.local:5000/docker-envdev-clang6:dev
  stage: build
  variables:
    CONAN_CLANG_VERSIONS: "6.0"
    CONAN_USE_CUDA: "True"
  script:
    - export CC=/usr/bin/clang-6.0
    - export CXX=/usr/bin/clang++-6.0
    - git -c http.sslVerify=false clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lan.local/conan/conan.git
    - python3 conan/gitlab-ci/build.py
    
macos:
  stage: build
  variables:
    CONAN_APPLE_CLANG_VERSIONS: "9.1"
    CONAN_USER_HOME: $CI_PROJECT_DIR
  script:
    - git -c http.sslVerify=false clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lan.local/conan/conan.git
    - python3 conan/gitlab-ci/build.py
  tags:
    - macos