variables:
  CONAN_REFERENCE: "pcl/1.8.1-rev-9dae1ea"
  CONAN_USERNAME: "fw4spl"
  CONAN_LOGIN_USERNAME: "fw4spl"
  CONAN_CHANNEL: "stable"
  CONAN_UPLOAD: "http://5.39.78.163:8081/artifactory/api/conan/conan-local"
  CONAN_STABLE_BRANCH_PATTERN: "stable/*"
  CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches "stable/*"
  CONAN_DOCKER_32_IMAGES: 1

stages:
  - build

msvc2015:
  image: greenjava/vcbuild2015:1.0
  stage: build
  script:
    - python build.py
  tags:
    - docker
    - windows

msvc2017:
  image: greenjava/vcbuild2017:1.0
  stage: build
  script:
    - python build.py
  tags:
    - docker
    - windows

.conan-template: &conan-template
  stage: build
  before_script:
    # Upgrade Conan version
    - sudo pip install --upgrade conan
    - sudo pip install conan_package_tools
    - conan user
  script:
    - python build.py

gcc-6:
  image: lasote/conangcc6
  variables:
      CONAN_GCC_VERSIONS: "6"
  <<: *conan-template

gcc-7:
  image: lasote/conangcc7
  variables:
      CONAN_GCC_VERSIONS: "7"
  <<: *conan-template

gcc-8:
  image: lasote/conangcc8
  variables:
      CONAN_GCC_VERSIONS: "8"
  <<: *conan-template

clang-5:
  image: lasote/conanclang50
  variables:
      CONAN_CLANG_VERSIONS: "5.0"
  <<: *conan-template

clang-6:
  image: lasote/conanclang60
  variables:
      CONAN_CLANG_VERSIONS: "6.0"
  <<: *conan-template